### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by bkuhls** [notspiff/visualization.fountain#1]
Hi, is it possible to add license information to the package?

**Comment by notspiff** [comment]
well thing is it's based on code without any license information https://svn.exotica.org.uk:8443/xbmc4xbox/trunk/sources/visualisations/Fountain/

i can assign a license to the bits i have rewritten, but i cannot do much more than that.

note that the visualization is not currently in a working shape.

**Comment by bkuhls** [comment]
Package was removed from buildroot in 2017, closing...
